-- Super-entidade
CREATE TABLE PESSOA(
    NOME VARCHAR(20) PRIMARY KEY,
    DT_NASC DATE,
    GENERO VARCHAR(1) NOT NULL,
    END_CEP VARCHAR(8) NOT NULL,
    END_BAIRRO VARCHAR(20) NOT NULL,
    LIDERA_GANGUE VARCHAR(20),
    FOREIGN KEY (LIDERA_GANGUE) REFERENCES GANGUE(NOME)
);

-- Sub-entidades
CREATE TABLE PROTAGONISTA(
    NOME VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME) REFERENCES PESSOA(NOME)

);

CREATE TABLE NPC(
    NOME VARCHAR(11) PRIMARY KEY,
    FOREIGN KEY (NOME) REFERENCES PESSOA(NOME)
);
-- ----------------------------------------------

-- Entidade fraca
CREATE TABLE MISSAO(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50) PRIMARY KEY,
    RECOMPENSA NUMERIC(10,2),
    FOREIGN KEY (NOME_PROTAGONISTA) REFERENCES PROTAGONISTA(NOME)
);

CREATE TABLE LOCAL(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50) PRIMARY KEY,
    NOME_LOCAL VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME_PROTAGONISTA,DESCRICAO) REFERENCES MISSAO(NOME_PROTAGONISTA,DESCRICAO)
);

/* CREATE TABLE GANGUE(
    LIDER VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    COR VARCHAR(20) NOT NULL,
    FOREIGN KEY (LIDER) REFERENCES PESSOA(CPF)
); */
-- ----------------------------------------------

-- Entidades regulares
/* CREATE TABLE MISSAO(
    NOME VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50),
    RECOMPENSA NUMERIC(10,2)
); */

/* CREATE TABLE LOCAL(
    NOME_MISSAO VARCHAR(20) PRIMARY KEY,
    NOME_LOCAL VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME_MISSAO) REFERENCES MISSAO(NOME)
); */

CREATE TABLE VEICULO(
    NOME VARCHAR(20) PRIMARY KEY,
    MARCA VARCHAR(20),
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE RADIO(
    NUMERO NUMERIC(3,1) PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL
);

CREATE TYPE ESTILOS_MUSICAIS AS ENUM (
    'POP',
    'ROCK',
    'ELETRONICA'
    'LOFI',
    'GOSPEL'
    'JAZZ',
    'FUNK',
    'BREGA',
);

CREATE TABLE MUSICA(
    NOME VARCHAR(20) PRIMARY KEY,
    GENERO1 ESTILOS_MUSICAIS NOT NULL,
    GENERO2 ESTILOS_MUSICAIS
);
-- ----------------------------------------------

-- Entidade associativa
CREATE TABLE FAZ(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50) PRIMARY KEY,
    FOREIGN KEY (NOME_PROTAGONISTA,DESCRICAO) REFERENCES MISSAO(NOME_PROTAGONISTA,DESCRICAO)
);

/* CREATE TABLE FAZ(
    PROTAGONISTA VARCHAR(11) PRIMARY KEY,
    NOME_MISSAO VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (PROTAGONISTA) REFERENCES PROTAGONISTA(CPF),
    FOREIGN KEY (NOME_MISSAO) REFERENCES MISSAO(NOME)
); */
-- ----------------------------------------------

-- Auto-relacionamento
CREATE TABLE AJUDA(
    AJUDANTE VARCHAR(20) PRIMARY KEY,
    AJUDADO VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (AJUDANTE) REFERENCES PROTAGONISTA(NOME),
    FOREIGN KEY (AJUDADO) REFERENCES PROTAGONISTA(NOME)
);
-- ----------------------------------------------

-- Relacionamentos
CREATE TABLE MATA(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    NOME_NPC VARCHAR(20) PRIMARY KEY,
    KILL_COUNT INTEGER PRIMARY KEY,
    FOREIGN KEY (PROTAGONISTA) REFERENCES PROTAGONISTA(NOME),
    FOREIGN KEY (NPC) REFERENCES NPC(NOME)
);

CREATE TABLE DIRIGE(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50) PRIMARY KEY,
    NOME_VEICULO VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME_PROTAGONISTA,DESCRICAO) REFERENCES FAZ(NOME_PROTAGONISTA,DESCRICAO),
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME)
);

-- Ternario
CREATE TABLE TOCA(
    NOME_VEICULO VARCHAR(20) PRIMARY KEY,
    NOME_MUSICA VARCHAR(20) PRIMARY KEY,
    NUMERO_RADIO NUMERIC(3,1) NOT NULL,
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME),
    FOREIGN KEY (NOME_MUSICA) REFERENCES MUSICA(NOME),
    FOREIGN KEY (NUMERO_RADIO) REFERENCES RADIO(NUMERO)
);
-- ----------------------------------------------