-- Super-entidade
CREATE TABLE PESSOA(
    CPF VARCHAR(11) PRIMARY KEY,
    PRIMEIRO_NOME VARCHAR(20) NOT NULL,
    SOBRENOME VARCHAR(20),
    DT_NASC DATE,
    GENERO VARCHAR(1),
    GANGUE VARCHAR(11),
    FOREIGN KEY (GANGUE) REFERENCES GANGUE(LIDER)
);

-- Sub-entidades
CREATE TABLE PROTAGONISTA(
    CPF VARCHAR(11) PRIMARY KEY,
    FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)

);

CREATE TABLE NPC(
    CPF VARCHAR(11) PRIMARY KEY,
    FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
);
-- ----------------------------------------------

-- Entidade fraca
CREATE TABLE GANGUE(
    LIDER VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    COR VARCHAR(20) NOT NULL,
    FOREIGN KEY (LIDER) REFERENCES PESSOA(CPF)
);
-- ----------------------------------------------

-- Entidades regulares
CREATE TABLE MISSAO(
    NOME VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50),
    RECOMPENSA NUMERIC(10,2)
);

CREATE TABLE LOCAL(
    NOME_MISSAO VARCHAR(20) PRIMARY KEY,
    NOME_LOCAL VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME_MISSAO) REFERENCES MISSAO(NOME)
);

CREATE TABLE VEICULO(
    NOME VARCHAR(20) PRIMARY KEY,
    MARCA VARCHAR(20),
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE RADIO(
    NUMERO NUMERIC(3,1) PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL
);

CREATE TYPE ESTILOS_MUSICAIS AS ENUM (
    'POP',
    'ROCK',
    'ELETRONICA'
    'LOFI',
    'GOSPEL'
    'JAZZ',
    'FUNK',
    'BREGA',
);

CREATE TABLE MUSICA(
    NOME VARCHAR(20) PRIMARY KEY,
    GENERO1 ESTILOS_MUSICAIS NOT NULL,
    GENERO2 ESTILOS_MUSICAIS
);
-- ----------------------------------------------

-- Entidade associativa
CREATE TABLE FAZ(
    PROTAGONISTA VARCHAR(11) PRIMARY KEY,
    NOME_MISSAO VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (PROTAGONISTA) REFERENCES PROTAGONISTA(CPF),
    FOREIGN KEY (NOME_MISSAO) REFERENCES MISSAO(NOME)
);
-- ----------------------------------------------

-- Auto-relacionamento
CREATE TABLE AJUDA(
    AJUDADO VARCHAR(11) PRIMARY KEY,
    AJUDADOR VARCHAR(11) PRIMARY KEY,
    FOREIGN KEY (AJUDADO) REFERENCES PROTAGONISTA(CPF),
    FOREIGN KEY (AJUDADOR) REFERENCES PROTAGONISTA(CPF)
);
-- ----------------------------------------------

-- Relacionamentos
CREATE TABLE MATA(
    PROTAGONISTA VARCHAR(11) PRIMARY KEY,
    NPC VARCHAR(11) PRIMARY KEY,
    KILL_COUNT INTEGER PRIMARY KEY,
    FOREIGN KEY (PROTAGONISTA) REFERENCES PROTAGONISTA(CPF),
    FOREIGN KEY (NPC) REFERENCES NPC(CPF)
);

CREATE TABLE DIRIGE(
    PROTAGONISTA VARCHAR(11) PRIMARY KEY,
    NOME_MISSAO VARCHAR(20) PRIMARY KEY,
    NOME_VEICULO VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (PROTAGONISTA,NOME_MISSAO) REFERENCES FAZ(PROTAGONISTA,NOME_MISSAO),
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME)
);

-- Ternario
CREATE TABLE TOCA(
    NOME_VEICULO VARCHAR(20) PRIMARY KEY,
    NOME_MUSICA VARCHAR(20) PRIMARY KEY,
    NUMERO_RADIO NUMERIC(3,1) NOT NULL,
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME),
    FOREIGN KEY (NOME_MUSICA) REFERENCES MUSICA(NOME)
);
-- ----------------------------------------------