-- Super-entidade
CREATE TABLE PESSOA(
    NOME VARCHAR(20) PRIMARY KEY,
    DT_NASC DATE NOT NULL,
    GENERO VARCHAR(1) NOT NULL,
    END_CIDADE VARCHAR(20) NOT NULL,
    END_BAIRRO VARCHAR(20) NOT NULL
);

-- Sub-entidades
CREATE TABLE PROTAGONISTA(
    NOME VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME) REFERENCES PESSOA(NOME)

);

CREATE TABLE NPC(
    NOME VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME) REFERENCES PESSOA(NOME)
);
-- ----------------------------------------------

-- Entidade fraca
CREATE TABLE MISSAO(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50) PRIMARY KEY,
    RECOMPENSA NUMERIC(10,2),
    FOREIGN KEY (NOME_PROTAGONISTA) REFERENCES PROTAGONISTA(NOME)
);
-- ----------------------------------------------

-- Entidades regulares

CREATE TABLE GANGUE(
    NOME VARCHAR(20) PRIMARY KEY,
    COR VARCHAR(20) NOT NULL
);

CREATE TABLE VEICULO(
    NOME VARCHAR(20) PRIMARY KEY,
    MARCA VARCHAR(20),
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE RADIO(
    NOME VARCHAR(20) PRIMARY KEY,
    NUMERO NUMERIC(3,1)
);

CREATE TYPE ESTILOS_MUSICAIS AS ENUM (
    'POP',
    'ROCK',
    'ELETRONICA'
    'LOFI',
    'GOSPEL'
    'JAZZ',
    'FUNK',
    'BREGA',
    'CLASSICA',
    'OPERA',
    'HIP-HOP',
    'RAP'
);

CREATE TABLE MUSICA(
    NOME VARCHAR(20) PRIMARY KEY,
    GENERO1 ESTILOS_MUSICAIS NOT NULL,
    GENERO2 ESTILOS_MUSICAIS
);

CREATE TABLE ROTINA(
    DESCRICAO VARCHAR(50) PRIMARY KEY,
    NOME_NPC VARCHAR(20) UNIQUE NOT NULL,
    FOREIGN KEY (NOME_NPC) REFERENCES NPC(NOME)
);
-- ----------------------------------------------

-- Entidade associativa
-- É o relacionamento identificador/entidade fraca: MISSAO
-- ----------------------------------------------

-- Auto-relacionamento
CREATE TABLE AJUDA(
    AJUDANTE VARCHAR(20) PRIMARY KEY,
    AJUDADO VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (AJUDANTE) REFERENCES PROTAGONISTA(NOME),
    FOREIGN KEY (AJUDADO) REFERENCES PROTAGONISTA(NOME)
);
-- ----------------------------------------------

-- Relacionamentos
CREATE TABLE MEMBRO(
    NOME_PESSOA VARCHAR(20) PRIMARY KEY,
    NOME_GANGUE VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME_PESSOA) REFERENCES PESSOA(NOME),
    FOREIGN KEY (NOME_GANGUE) REFERENCES GANGUE(NOME)
);

CREATE TABLE MATA(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    NOME_NPC VARCHAR(20) PRIMARY KEY,
    KILL_COUNT INTEGER PRIMARY KEY,
    FOREIGN KEY (NOME_PROTAGONISTA) REFERENCES PROTAGONISTA(NOME),
    FOREIGN KEY (NOME_NPC) REFERENCES NPC(NOME)
);

CREATE TABLE DIRIGE(
    NOME_PROTAGONISTA VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(50) PRIMARY KEY,
    NOME_VEICULO VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (NOME_PROTAGONISTA,DESCRICAO) REFERENCES MISSAO(NOME_PROTAGONISTA,DESCRICAO),
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME)
);

-- Ternario
CREATE TABLE TOCA(
    NOME_VEICULO VARCHAR(20) PRIMARY KEY,
    NOME_MUSICA VARCHAR(20) PRIMARY KEY,
    NOME_RADIO VARCHAR(20) NOT NULL,
    FOREIGN KEY (NOME_VEICULO) REFERENCES VEICULO(NOME),
    FOREIGN KEY (NOME_MUSICA) REFERENCES MUSICA(NOME),
    FOREIGN KEY (NOME_RADIO) REFERENCES RADIO(NOME)
);
-- ----------------------------------------------